FROM quorum/frontdev
MAINTAINER DANIEL jean-Baptiste - Quorum

ADD . /srv/http/corporate/public/priocd17

WORKDIR /srv/http/corporate/public/priocd17

VOLUME ["/srv/http/corporate/public/priocd17"]

CMD ["/bin/true"]
